### ISSUE TITLE
Package "url" is intended for the conan-expat repository

### ISSUE THREAD

**Issue by memsharded** [Pix4D/conan-expat#2]
The URL in the conanfile.py is intended to direct to the package repo, the place where the recipe lives. Someone reading the conanfile.py meta-data is typically concerned about the package, not the original source code.

Other users typically use 2 URLS, one ``source_url`` or similar, for the original repo, and ``url`` in this case should be: ``https://github.com/Pix4D/conan-expat``

**Comment by piponazo** [comment]
I have addressed this issue and the other one in the branch: **fixIssues**. Please let me know if I can do something else to improve the recipe.
