### ISSUE TITLE
Improve package_info()

### ISSUE THREAD

**Issue by memsharded** [Pix4D/conan-expat#3]
Current one is:
```python
    def package_info(self):
        self.cpp_info.debug.libs = ["expatd"]
        self.cpp_info.release.libs = ["expat"]
        self.cpp_info.libdirs = ["lib"]
        self.cpp_info.includedirs = ["include"]
        if not self.options.shared:
            self.cpp_info.defines = ["XML_STATIC"]
```

The ``libdirs`` and ``includedirs`` are already the defaults, can be omitted

A question: is the package multi-config package? In that case, it should declare ``build_type`` as a setting. If it is not, it should do something like:
```python
    def package_info(self):
        if self.settings.build_type == "Debug":
               self.cpp_info.libs = ["expatd"]
        else:
               self.cpp_info.libs = ["expat"]
```

**Comment by piponazo** [comment]
Sorry for the delay in my answer I was in holidays and I completely forgot about this.

I am not sure what does it mean to be a multi-config package ? Is a property of the project itself , or of the conan recipe ? Can you point me to the conan.io documentation regarding to this ?

I have checked that the name of the library is always libexpat either if the build type is Release or Debug.  Would it be enough to simply use:

```
self.cpp_info.libs = ["expat"]
```
For both cases ?

**Comment by piponazo** [comment]
I have addressed this issue and the other one in the branch: **fixIssues**. Please let me know if I can do something else to improve the recipe.

**Comment by piponazo** [comment]
Ouch ... great, AppVeyor helps me to discover that on Windows there is a difference between the Release and Debug builds (expat.lib and expatd.lib).
